runtime: python27
api_version: 1
version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /receive_message.*
  script: main.APPLICATION
- url: /.*
  script: main.APPLICATION
  login: admin

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
